
-- DROP SEQUENCE SEQ_BILLING_METRIC_ID;

-- CREATE SEQUENCE SEQ_TRIP_ADVISOR_USER_ID INCREMENT BY 1 START WITH 100;

CREATE TABLE TRIP_ADVISOR_USER(
ID INTEGER NOT NULL,
NICKNAME VARCHAR(255),
PASSWORD VARCHAR(255),
FIRST_NAME VARCHAR(255),
LAST_NAME VARCHAR(255),
EMAIL VARCHAR(255),
NOTIFY_MY VARCHAR(255),
PRIMARY KEY(ID));