CREATE SEQUENCE SEQ_TRIP_ADVISOR_USER_ID INCREMENT BY 1 START WITH 1;

CREATE TABLE TRIP_ADVISOR_USER(
ID NUMBER(19,0) NOT NULL PRIMARY KEY,
NICKNAME VARCHAR(255 char),
PASSWORD VARCHAR(255 char),
FIRST_NAME VARCHAR(255 char),
LAST_NAME VARCHAR(255 char),
EMAIL VARCHAR(255 char),
NOTIFY_MY BIT);